export const ERROR_CODES = {
    AUTH_MISSING_FIELDS: 'AUTH_MISSING_FIELDS',
    AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
    AUTH_REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
    AUTH_INVALID_USERNAME: 'AUTH_INVALID_USERNAME',
    AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',

    ARMY_NOT_FOUND: 'ARMY_NOT_FOUND',
    ARMY_FETCH_ERROR: 'ARMY_FETCH_ERROR',
    ARMY_CREATE_ERROR: 'ARMY_CREATE_ERROR',
    ARMY_UPDATE_ERROR: 'ARMY_UPDATE_ERROR',
    ARMY_DELETE_ERROR: 'ARMY_DELETE_ERROR',

    DETACHMENT_CREATE_ERROR: 'Failed to create detachment',
    DETACHMENT_FETCH_ERROR: 'DETACHMENT_FETCH_ERROR',
    DETACHMENT_NOT_FOUND: 'DETACHMENT_NOT_FOUND',
    DETACHMENT_RETRIEVE_ERROR: 'DETACHMENT_RETRIEVE_ERROR',
    DETACHMENT_DELETE_ERROR: 'DETACHMENT_DELETE_ERROR',
    DETACHMENT_UPDATE_ERROR: 'DETACHMENT_UPDATE_ERROR',
    
    MATCH_CREATE_FAILED: 'MATCH_CREATE_FAILED',
    MATCH_FETCH_FAILED: 'MATCH_FETCH_FAILED',
    MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
    MATCH_RETRIEVE_FAILED: 'MATCH_RETRIEVE_FAILED',
    MATCH_DELETE_FAILED: 'MATCH_DELETE_FAILED',
    MATCH_UPDATE_FAILED: 'MATCH_UPDATE_FAILED'
}